### ISSUE TITLE
AWSElasticBeanstalkCreateEnvironmentTask cannot update environment due to Tier limitation

### ISSUE THREAD

**Issue by esword** [classmethod-aws/gradle-aws-plugin#10]
I tried to use the task to change the deployed version of the app, and AWS returned this error:

 Cannot change environment tier (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue

I am not trying to set the Tier, so this was confusing. The problem is that the environment's current tier does not have a version string (or it is not being returned as part of the describe call):

Tier: {Name: WebServer,Type: Standard,Version:  }

But the task tries to set a tier with a version.  I tried setting the tier to null, but then line 87 of AWSElasticBeanstalkCreateEnvironmentTask will get a NullPointerError.  I then pulled a branch of the project and changed line 87 to do a safe dereference:

.withTier(tier?.toEnvironmentTier()))

This works.  I set tier to null in my gradle file and the task will update the environment properly.  Can you apply this change to the main build?  Another option is to not include Tier in an update command because it is very rare that you would need to ever change it.

**Comment by slively** [comment]
This is currently blocking me, sent a PR.

**Comment by miyamoto-daisuke** [comment]
@slively Sorry for my late reply.
This PR completely ignores the `tier` parameter of AWSElasticBeanstalkCreateEnvironmentTask.
We should call `withTier` method if `tier` is not null like following:
```
if (tier != null) {
	req.withTier(tier.toEnvironmentTier());
}
```

**Comment by slively** [comment]
It's been working for me so far. It doesn't seem necessary only because it's not a required field, but I guess it wouldn't work for people creating a worker tier. I'll send an update. I've since forked and hosted locally to keep working, thank you for responding and this awesome plugin. Super useful!
