### ISSUE TITLE
JDK 1.7 build?

### ISSUE THREAD

**Issue by esword** [classmethod-aws/gradle-aws-plugin#3]
Any chance you could do a release with sourceCompatibility = '1.7'?

**Comment by watanabeshuji** [comment]
sorry
I challenged to build for Java7.
but I can't run under Java7, because groovy's version conflict.
If you can PR for Java7, we'are happy together!

**Comment by esword** [comment]
You don't have to run or compile under JDK 7.  Just set the source
compatibility for that so your compiled classes can be run under it.

Just put this near the top of your build.gradle

sourceCompatibility = '1.7'

**Comment by ajbrown** [comment]
+1
