### ISSUE TITLE
S3 File Upload Tasks will overwrite changed files even when overwrite = false

### ISSUE THREAD

**Issue by ajbrown** [classmethod-aws/gradle-aws-plugin#4]
On [this line](https://github.com/classmethod-aws/gradle-aws-plugin/blob/0.13.2/src/main/groovy/jp/classmethod/aws/gradle/s3/AmazonS3FileUploadTask.groovy#L56), The upload will be attempted if any of the following is true:

- overwrite = true
- there is no metadata for the file
- the MD5 hash is not the same as the local version of the file.

This doesn't seem like the desirable behavior.   The third condition should probably be seperate from the first two -- upload if overwrites are allowed or there is no metadata, AND the md5 hash is different.

Especially when you set overwrite like this:

``` overwrite version.endsWith("-SNAPSHOT") ```

**Comment by miyamoto-daisuke** [comment]
OK, it should be ```if (metadata == null || (overwrite && metadata.getETag() != md5())) {```
